language: ruby
cache: bundler

rvm:
 - 2.3
 - jruby
 - rbx-3

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - johnteckert@gmail.com
    on_failure: change
    on_success: never
